"""O22.3 deterministic tribunal contract."""

ORDER = "O22.3"
PARENT_ORDER = "O22.2"
PARENT_SHA = "e469b447d497f6533487fbf9098b1a6152d2d494"
VERSION = "omnipath.pathology-tribunal/v1"
REQUIRED_PATHOLOGIES = frozenset({
    "FALSE_CONSENSUS",
    "PROVENANCE_LOSS",
    "OBSERVER_COLLAPSE",
    "CONTRADICTION_ERASURE",
    "REPLAY_DIVERGENCE",
    "LINEAGE_CORRUPTION",
})
ALLOWED_CORRUPTED_DECISIONS = frozenset({"QUARANTINE", "REJECT"})
